### PR TITLE
Fix composite parameters

### LINKED ISSUE #421: Version 2.2 fails loading fixtures
After recent update to 2.2 version i've got this:

>
[Hautelook\AliceBundle\Alice\DataFixtures\LoadingLimitException]                            
  Loading files limit of 50 reached. Could not load the following files 
/code/src/AppBundle/DataFixtures/ORM/changelogs.yml:                                        
   - Entity with ID @user-1 and class Mailer\AuthBundle\Entity\User not found

And the same for every fixtures file, where references are present.

Version 2.1.4 works fine. Has anyone faced this problem too?

### PR DESCRIPTION
**Pull request by theofidry**
In b80fdfa (https://github.com/nelmio/alice/pull/355), the Processor method Parameterized has been refactored to be more readable and robust. In the process, a non covered case involving composite keys has been broken. This commit fix the BC break introduced and add a test case for it.

Related to #421.

### CODE REVIEW

File: tests/Nelmio/Alice/Fixtures/LoaderTest.php [hunk 1]
```diff
@@ -1707,30 +1707,40 @@ public function testArrayParametersLoading()
...
-        $user = $res['user0'];
+        $user = $objects['user0'];
+        $this->assertInstanceOf(self::USER, $user);
+        //$this->assertEquals('NaN Bat!', $user->username); Not supported yet
+        $this->assertEquals('<{key1}> <{key2}>!', $user->username);
+
+        $user = $objects['user1'];
         $this->assertInstanceOf(self::USER, $user);
-        $this->assertEquals('Nan Bat!', $user->username);
+        //$this->assertEquals('NaN Bat!', $user->username); Not supported yet
```
Comment (Soullivaneuh) [inline tests/Nelmio/Alice/Fixtures/LoaderTest.php]: This commented code should not be here IMHO.

File: tests/Nelmio/Alice/Fixtures/LoaderTest.php [hunk 2]
```diff
@@ -1707,30 +1707,40 @@ public function testArrayParametersLoading()
...
-        $res = $this->createLoader()->load(__DIR__ . '/Files/parameters/composite.yml');
+        $objects = $this->createLoader()->load(__DIR__ . '/Files/parameters/composite.yml');
 
-        $this->assertCount(1, $res);
+        $this->assertCount(2, $objects);
 
-        $user = $res['user0'];
+        $user = $objects['user0'];
+        $this->assertInstanceOf(self::USER, $user);
+        //$this->assertEquals('NaN Bat!', $user->username); Not supported yet
```
Comment (Soullivaneuh) [inline tests/Nelmio/Alice/Fixtures/LoaderTest.php]: This commented code should not be here IMHO.

**Comment by Soullivaneuh** [comment]
Seems to not fix my issue:

```
  [Hautelook\AliceBundle\Alice\DataFixtures\LoadingLimitException]                                                             
  Loading files limit of 5 reached. Could not load the following files:                                                        
  /code/src/AppBundle/DataFixtures/ORM/cron.yml:                                                                               
   - Instance mask "domain_*" did not match any existing instance, make sure the object is created after its references        
  /code/src/AppBundle/DataFixtures/ORM/domain.yml:                                                                             
   - Instance mask "server_nx102*" did not match any existing instance, make sure the object is created after its references   
  /code/src/AppBundle/DataFixtures/ORM/incident.yml:                                                                           
   - Instance mask "server_*" did not match any existing instance, make sure the object is created after its references        
  /code/src/AppBundle/DataFixtures/ORM/ip_v4.yml:                                                                              
   - Instance server_default is not defined                                                                                    
  /code/src/AppBundle/DataFixtures/ORM/operation.yml:                                                                          
   - Instance cron_98 is not defined                                                                                           
   - Instance cron_95 is not defined                                                                                           
   - Instance cron_6 is not defined                                                                                            
   - Instance cron_99 is not defined                                                                                           
   - Instance cron_49 is not defined                                                                                           
   - Instance cron_41 is not defined                                                                                           
  /code/src/AppBundle/DataFixtures/ORM/package.yml:                                                                            
   - Instance mask "server_*" did not match any existing instance, make sure the object is created after its references        
  /code/src/AppBundle/DataFixtures/ORM/puppet.yml:                                                                             
   - Entity with ID @puppet_package_www-servers_apache and class AppBundle\Entity\PuppetPackage not found                      
  /code/src/AppBundle/DataFixtures/ORM/server.yml:                                                                             
   - Instance os_gentoo is not defined                                                                                         
   - Instance mask "puppet_class_*" did not match any existing instance, make sure the object is created after its references  
  /code/src/AppBundle/DataFixtures/ORM/service_ip.yml:                                                                         
   - Instance mask "server_*" did not match any existing instance, make sure the object is created after its references        
```

File: tests/Nelmio/Alice/Fixtures/LoaderTest.php (hunk 2 above)
Comment (theofidry) [inline tests/Nelmio/Alice/Fixtures/LoaderTest.php]: I would like to keep it to show what *it should be*... but I can understand that people don't want comments

**Comment by theofidry** [comment]
@Soullivaneuh is there any way to get access to a repo where I can reproduce the bug?

**Comment by Soullivaneuh** [comment]
@theofidry Sadly no. This is a private project.

I can give you some info:

```bash
$ ./docker-console composer show nelmio/alice
name     : nelmio/alice
descrip. : Expressive fixtures generator
keywords : Fixture, data, orm, test
versions : * 2.1.4
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source   : [git] https://github.com/theofidry/alice.git 00b3565132cd69acacc7f7ffbe856af62a26f1a0
dist     : [zip] https://api.github.com/repos/theofidry/alice/zipball/00b3565132cd69acacc7f7ffbe856af62a26f1a0 00b3565132cd69acacc7f7ffbe856af62a26f1a0
names    : nelmio/alice

autoload
psr-4
Nelmio\Alice\ => src/Nelmio/Alice

requires
fzaninotto/faker ~1.0
php >=5.4
symfony/yaml ~2.0|~3.0

requires (dev)
doctrine/common ~2.3
phpunit/phpunit ~4.0
symfony/property-access ~2.2|~3.0
```

```yaml
hautelook_alice:
    locale: fr_FR
    seed: 6399
```

I will test with https://github.com/hautelook/AliceBundle/pull/238 too.

**Comment by Soullivaneuh** [comment]
With alice-bundle PR and this one, I got this:

```
  [UnexpectedValueException]              
  Instance user_support_4 is not defined  
```

**Comment by theofidry** [comment]
@Soullivaneuh I'm going to merge this one as it's a blocker. Let's continue the investigation for your bit in the original issue.
